// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsvtwuyhzaoqqpygjwgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzdnR3dXloemFvcXFweWdqd2dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzQxNDIsImV4cCI6MjA2OTcxMDE0Mn0.G2CEXxp70IHi1ZVOk_KOK57IqXF6JfPUv0DPbnPPxRU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});